import React from "react";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import { pdf } from "@react-pdf/renderer";
import type { ProductSheetData } from "./product-sheet-utils";

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", fontSize: 10, color: "#1a1a1a" },
  // Page 1
  header: { marginBottom: 20 },
  title: { fontSize: 28, fontWeight: "bold", color: "#1e3a5f", marginBottom: 4 },
  subtitle: { fontSize: 12, color: "#6b7280" },
  badge: {
    backgroundColor: "#10b981",
    color: "#ffffff",
    fontSize: 8,
    fontWeight: "bold",
    padding: "3 8",
    borderRadius: 4,
    alignSelf: "flex-start",
    marginTop: 8,
  },
  descriptionBox: {
    marginTop: 20,
    padding: 16,
    backgroundColor: "#f8fafc",
    borderRadius: 6,
    borderLeft: "4 solid #3b82f6",
  },
  descriptionTitle: { fontSize: 12, fontWeight: "bold", color: "#1e40af", marginBottom: 6 },
  descriptionText: { fontSize: 10, lineHeight: 1.6, color: "#374151" },
  // Feature badges
  featureRow: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginTop: 16 },
  featureBadge: {
    backgroundColor: "#eff6ff",
    color: "#1d4ed8",
    fontSize: 8,
    fontWeight: "bold",
    padding: "4 10",
    borderRadius: 12,
  },
  // Page 2
  sectionTitle: { fontSize: 14, fontWeight: "bold", color: "#1e3a5f", marginBottom: 12, marginTop: 20 },
  specGrid: { flexDirection: "row", flexWrap: "wrap" },
  specItem: { width: "50%", marginBottom: 12, paddingRight: 8 },
  specLabel: { fontSize: 8, color: "#9ca3af", textTransform: "uppercase", letterSpacing: 0.5, marginBottom: 2 },
  specValue: { fontSize: 14, fontWeight: "bold", color: "#111827" },
  // Footer
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    borderTop: "1 solid #e5e7eb",
    paddingTop: 8,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  footerText: { fontSize: 7, color: "#9ca3af" },
  verifiedBadge: {
    backgroundColor: "#dcfce7",
    color: "#166534",
    fontSize: 7,
    fontWeight: "bold",
    padding: "2 6",
    borderRadius: 3,
  },
});

function ProductSheetDocument({ data }: { data: ProductSheetData }) {
  return (
    <Document>
      {/* Page 1: Hero + Description */}
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{data.title}</Text>
          <Text style={styles.subtitle}>{data.game_type}</Text>
          {data.simulation_verified && (
            <View style={styles.badge}>
              <Text>MATH VERIFIED</Text>
            </View>
          )}
        </View>

        {data.description && (
          <View style={styles.descriptionBox}>
            <Text style={styles.descriptionTitle}>Game Description</Text>
            <Text style={styles.descriptionText}>{data.description}</Text>
          </View>
        )}

        {data.features.length > 0 && (
          <View>
            <Text style={[styles.sectionTitle, { marginTop: 24 }]}>Features</Text>
            <View style={styles.featureRow}>
              {data.features.map((f, i) => (
                <View key={i} style={styles.featureBadge}>
                  <Text>{f}</Text>
                </View>
              ))}
            </View>
          </View>
        )}

        {/* Key specs preview */}
        <View style={{ marginTop: 30 }}>
          <Text style={styles.sectionTitle}>Key Metrics</Text>
          <View style={styles.specGrid}>
            <View style={styles.specItem}>
              <Text style={styles.specLabel}>RTP</Text>
              <Text style={styles.specValue}>{data.rtp}</Text>
            </View>
            <View style={styles.specItem}>
              <Text style={styles.specLabel}>Volatility</Text>
              <Text style={styles.specValue}>{data.volatility}</Text>
            </View>
            <View style={styles.specItem}>
              <Text style={styles.specLabel}>Max Win</Text>
              <Text style={styles.specValue}>{data.max_win}</Text>
            </View>
            <View style={styles.specItem}>
              <Text style={styles.specLabel}>Grid</Text>
              <Text style={styles.specValue}>{data.grid}</Text>
            </View>
          </View>
        </View>

        <View style={styles.footer}>
          <Text style={styles.footerText}>Generated by SlotCraft</Text>
          <Text style={styles.footerText}>Page 1 of 2</Text>
        </View>
      </Page>

      {/* Page 2: Full Specs */}
      <Page size="A4" style={styles.page}>
        <Text style={[styles.title, { fontSize: 18 }]}>{data.title} — Technical Specifications</Text>

        <Text style={styles.sectionTitle}>Game Configuration</Text>
        <View style={styles.specGrid}>
          <View style={styles.specItem}>
            <Text style={styles.specLabel}>Game Type</Text>
            <Text style={styles.specValue}>{data.game_type}</Text>
          </View>
          <View style={styles.specItem}>
            <Text style={styles.specLabel}>Grid Layout</Text>
            <Text style={styles.specValue}>{data.grid}</Text>
          </View>
          <View style={styles.specItem}>
            <Text style={styles.specLabel}>Paylines</Text>
            <Text style={styles.specValue}>{data.paylines}</Text>
          </View>
          <View style={styles.specItem}>
            <Text style={styles.specLabel}>Bet Range</Text>
            <Text style={styles.specValue}>{data.bet_range}</Text>
          </View>
        </View>

        <Text style={styles.sectionTitle}>Math Parameters</Text>
        <View style={styles.specGrid}>
          <View style={styles.specItem}>
            <Text style={styles.specLabel}>Return to Player (RTP)</Text>
            <Text style={styles.specValue}>{data.rtp}</Text>
          </View>
          <View style={styles.specItem}>
            <Text style={styles.specLabel}>Volatility</Text>
            <Text style={styles.specValue}>{data.volatility}</Text>
          </View>
          <View style={styles.specItem}>
            <Text style={styles.specLabel}>Hit Frequency</Text>
            <Text style={styles.specValue}>{data.hit_frequency}</Text>
          </View>
          <View style={styles.specItem}>
            <Text style={styles.specLabel}>Maximum Win</Text>
            <Text style={styles.specValue}>{data.max_win}</Text>
          </View>
        </View>

        {data.simulation_verified && (
          <View>
            <Text style={styles.sectionTitle}>Verification</Text>
            <View style={{ flexDirection: "row", alignItems: "center", gap: 8 }}>
              <View style={styles.verifiedBadge}>
                <Text>VERIFIED</Text>
              </View>
              <Text style={{ fontSize: 9, color: "#374151" }}>
                Monte Carlo simulation ({data.simulation_spins} spins) confirms RTP within tolerance.
              </Text>
            </View>
          </View>
        )}

        {data.art_style && (
          <View>
            <Text style={styles.sectionTitle}>Art Direction</Text>
            <Text style={styles.descriptionText}>{data.art_style}</Text>
          </View>
        )}

        {data.markets.length > 0 && (
          <View>
            <Text style={styles.sectionTitle}>Target Markets</Text>
            <View style={styles.featureRow}>
              {data.markets.map((m, i) => (
                <View key={i} style={styles.featureBadge}>
                  <Text>{m.replace("_", " ").toUpperCase()}</Text>
                </View>
              ))}
            </View>
          </View>
        )}

        <View style={styles.footer}>
          <Text style={styles.footerText}>
            Generated by SlotCraft on {new Date().toLocaleDateString()}
          </Text>
          <Text style={styles.footerText}>Page 2 of 2</Text>
        </View>
      </Page>
    </Document>
  );
}

export async function generateProductSheetPdf(data: ProductSheetData): Promise<Blob> {
  return pdf(<ProductSheetDocument data={data} />).toBlob();
}
